name: End-to-end tests

on:
  push:
    branches:
      - dev  # ou a branch que você usa
  pull_request:
    branches:
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Se o package.json está em uma subpasta, navegue até ela
      - name: Navigate to project directory
        run: cd Cypress-bugbank  # Caso o 'package.json' esteja dentro da pasta Cypress-bugbank

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
