name: Cypress Tests with Qase.io

on:
  push:
    branches:
      - main  # ou a branch que você usar
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    # Defina os passos a serem executados
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Cypress Tests
        env:
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}  # Token do Qase, armazenado nos secrets do GitHub
          QASE_PROJECT_CODE: ${{ secrets.QASE_PROJECT_CODE }}  # Código do projeto no Qase.io, também armazenado nos secrets do GitHub
        run: |
          npx cypress run
