name: End-to-end tests

on:
  push:
    branches:
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Install Cypress binary
        run: |
          npx cypress install

      - name: Grant execute permissions to Cypress binary
        run: |
          chmod -R 777 ./node_modules/.bin/cypress
          chmod -R 777 ./node_modules/cypress

      - name: Run Cypress tests
        env:
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
          QASE_PROJECT_CODE: ${{ secrets.QASE_PROJECT_CODE }}
        run: |
          npx cypress run
